'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BoggleGame.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property boggle_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("boggle_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boggle_textmark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boggle_textmark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DO WHAT THE F*CK YOU WANT TO PUBLIC LICENSE
        '''                    Version 2, December 2004
        '''
        ''' Copyright (C) 2004 Sam Hocevar &lt;sam@hocevar.net&gt;
        '''
        ''' Everyone is permitted to copy and distribute verbatim or modified
        ''' copies of this license document, and changing it is allowed as long
        ''' as the name is changed.
        '''
        '''            DO WHAT THE F*CK YOU WANT TO PUBLIC LICENSE
        '''   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
        '''
        '''  0. You just DO WHAT THE F*CK YOU WANT TO..
        '''</summary>
        Friend ReadOnly Property COPYING() As String
            Get
                Return ResourceManager.GetString("COPYING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ding() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to aback
        '''abacus
        '''abalone
        '''abandon
        '''abase
        '''abash
        '''abate
        '''abater
        '''abbas
        '''abbe
        '''abbey
        '''abbot
        '''abbreviate
        '''abc
        '''abdicate
        '''abdomen
        '''abdominal
        '''abduct
        '''abed
        '''aberrant
        '''aberrate
        '''abet
        '''abetted
        '''abetting
        '''abeyance
        '''abeyant
        '''abhorred
        '''abhorrent
        '''abide
        '''abject
        '''ablate
        '''ablaze
        '''able
        '''ablution
        '''abnormal
        '''aboard
        '''abode
        '''abolish
        '''abolition
        '''abominable
        '''abominate
        '''aboriginal
        '''aborigine
        '''aborning
        '''abort
        '''abound
        '''about
        '''above
        '''aboveboard
        '''aboveground
        '''abovementioned
        '''abrade
        '''abrasion
        '''abrasive
        '''abreact
        '''abreast
        '''abridge
        '''abridgment
        '''abroad
        '''abrogate
        '''abrupt
        '''abscess
        '''abscissa
        '''abscissae
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property lexicon() As String
            Get
                Return ResourceManager.GetString("lexicon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_WindowsAPICodePack() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_WindowsAPICodePack", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Microsoft_WindowsAPICodePack_Shell() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft_WindowsAPICodePack_Shell", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
